In [5]:
# coding=utf-8
# Copyright 2020 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Training and evaluation"""

from absl import app
from absl import flags
from ml_collections.config_flags import config_flags
import logging
import os
import tensorflow as tf
import sys 
import datasets 

# sys.argv = = [ '--dataset', 'SMD', '--q', '0.005']

# sys.argv = ['--workdir',  'results/cifar10/', '--config', 'configs/subvp/cifar10_ddpm_continuous.py',  '--mode', 'train']
# 
#         

from configs.default_cifar10_configs import get_default_configs


config = get_default_configs()

config.data.dataset = 'CIFAR10_ADJ_ID_1'

train_ds, eval_ds, _ = datasets.get_dataset(config,
                                  uniform_dequantization=config.data.uniform_dequantization, 
                                            evaluation=True)




building train
building test
splits done
Applying Filters for Adjacent OOD Benchmark
In distribution classes are [2 9 6 4 0 3 1 7]


In [ ]:
import tensorflow_datasets as tfds 

train, test = tfds.load('cifar10', split=['train','test'])

In [2]:
for data in eval_ds: 
    break 
    
tf.unique(data['label'])


Unique(y=<tf.Tensor: shape=(8,), dtype=int64, numpy=array([3, 8, 2, 9, 4, 7, 1, 6], dtype=int64)>, idx=<tf.Tensor: shape=(1024,), dtype=int32, numpy=array([0, 1, 2, ..., 1, 1, 6])>)

In [14]:
data['image']

<tf.Tensor: shape=(1024, 32, 32, 3), dtype=float32, numpy=
array([[[[0.79215693, 0.7960785 , 0.8117648 ],
         [0.78823537, 0.79215693, 0.8078432 ],
         [0.7843138 , 0.78823537, 0.80392164],
         ...,
         [0.9215687 , 0.92549026, 0.9607844 ],
         [0.9215687 , 0.9333334 , 0.96470594],
         [0.92549026, 0.93725497, 0.9686275 ]],

        [[0.75294125, 0.7568628 , 0.7725491 ],
         [0.75294125, 0.7568628 , 0.7725491 ],
         [0.75294125, 0.7568628 , 0.7725491 ],
         ...,
         [0.91372555, 0.9176471 , 0.9607844 ],
         [0.91372555, 0.92549026, 0.96470594],
         [0.9176471 , 0.9294118 , 0.96470594]],

        [[0.7372549 , 0.7411765 , 0.7568628 ],
         [0.7372549 , 0.7411765 , 0.7568628 ],
         [0.7372549 , 0.7411765 , 0.7568628 ],
         ...,
         [0.9058824 , 0.909804  , 0.9607844 ],
         [0.9058824 , 0.91372555, 0.96470594],
         [0.909804  , 0.9176471 , 0.96470594]],

        ...,

        [[0.7960785 , 0.79215693,

In [7]:
import os
import pandas as pd
from torch.utils.data import Dataset
import numpy as np
from PIL import Image


class FaceDataset(Dataset):
    # https://www.kaggle.com/competitions/challenges-in-representation-learning-facial-expression-recognition-challenge/data?select=icml_face_data.csv
    def __init__(
        self,
        df,
        transform=None,
    ):
        self.df = df.to_dict("records")

        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df[idx]

        label = row["emotion"]
        pixels = row[" pixels"]

        pixels = np.array(pixels.split()).astype(int)
        pixels = np.reshape(pixels, (48, 48))
        pixels = np.expand_dims(pixels, axis=-1)
        image = np.repeat(pixels, 3, axis=-1)
        image = np.uint8(image)
        image = Image.fromarray(image)

        if self.transform:
            image = self.transform(image)

        return image, label

df = pd.read_csv("data/icml_face_data.csv")

face_datset = FaceDataset(df=df)







In [13]:
from tqdm import tqdm 

images = []
labels = [] 

for data in tqdm(face_datset):
    data[0]
    
    break 
i



 18%|█▊        | 6629/35887 [00:05<00:23, 1223.97it/s]


KeyboardInterrupt: 

{8: 0, 1: 1, 5: 2, 0: 3, 7: 4, 2: 5, 9: 6, 4: 7}

1024

Unique(y=<tf.Tensor: shape=(2,), dtype=int64, numpy=array([3, 6], dtype=int64)>, idx=<tf.Tensor: shape=(1024,), dtype=int32, numpy=array([0, 0, 1, ..., 1, 0, 1])>)

<tf.Tensor: shape=(), dtype=bool, numpy=True>