In [1]:
# coding=utf-8
# Copyright 2020 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Training and evaluation"""

from absl import app
from absl import flags
from ml_collections.config_flags import config_flags
import logging
import os
import tensorflow as tf
import sys 
import datasets 

# sys.argv = = [ '--dataset', 'SMD', '--q', '0.005']

# sys.argv = ['--workdir',  'results/cifar10/', '--config', 'configs/subvp/cifar10_ddpm_continuous.py',  '--mode', 'train']
# 
#         

from configs.adj.cifar10_configs_0_id import get_default_configs
import tensorflow_datasets as tfds 
from tqdm import tqdm 

config = get_default_configs()

config.data.dataset = 'ICML_FACE_ADJ_ID_0'

train_ds, eval_ds, _ = datasets.get_dataset(config,
                                  uniform_dequantization=config.data.uniform_dequantization, 
                                            evaluation=True, 
                                            recon=True
                                            )




building train
building test
splits done
Applying Filters for Adjacent OOD Benchmark
In distribution classes are [0, 1, 2, 3, 6]


In [3]:
import pandas as pd 


# ds = tfds.load('cars196', split='train', shuffle_files=True)
# 

for data in train_ds:
    break 
    
data['image']



<tf.Tensor: shape=(64, 64, 3), dtype=uint8, numpy=
array([[[ 70,  70,  70],
        [ 76,  76,  76],
        [ 80,  80,  80],
        ...,
        [ 46,  46,  46],
        [ 42,  42,  42],
        [ 41,  41,  41]],

       [[ 67,  67,  67],
        [ 67,  67,  67],
        [ 67,  67,  67],
        ...,
        [ 50,  50,  50],
        [ 46,  46,  46],
        [ 42,  42,  42]],

       [[ 59,  59,  59],
        [ 56,  56,  56],
        [ 55,  55,  55],
        ...,
        [ 53,  53,  53],
        [ 50,  50,  50],
        [ 45,  45,  45]],

       ...,

       [[ 82,  82,  82],
        [ 78,  78,  78],
        [ 71,  71,  71],
        ...,
        [ 75,  75,  75],
        [ 57,  57,  57],
        [ 44,  44,  44]],

       [[ 77,  77,  77],
        [ 77,  77,  77],
        [ 79,  79,  79],
        ...,
        [ 92,  92,  92],
        [ 75,  75,  75],
        [ 59,  59,  59]],

       [[ 77,  77,  77],
        [ 74,  74,  74],
        [ 76,  76,  76],
        ...,
        [108, 108, 108]

In [10]:
import matplotlib.pyplot as plt

# plt.imshow(data['image'].numpy())


data['label']

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [8]:
# !pip install matplotlib